apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jenkins-pipeline-secrets
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-backend
  target:
    name: jenkins-pipeline-secrets
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: jenkins-github-token
    - secretKey: ARGOCD_TOKEN
      remoteRef:
        key: jenkins-argocd-token