apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-backend
spec:
  provider:
    gcpsm:
      projectID: andrei-innowise-tests-120826
      auth:
        workloadIdentity:
          clusterLocation: europe-north1-a
          clusterName: gke-private-cluster
          serviceAccountRef:
            name: jenkins-sa
            namespace: jenkins