apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-config
  namespace: jenkins
data:
  jenkins.yaml: |
    jenkins:
      slaveAgentPort: 50000
      securityRealm:
        local:
          allowsSignup: false
          users:
            - id: "admin"
              password: "AdminPassword123!"
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false
      clouds:
        - kubernetes:
            name: "kubernetes"
            serverUrl: "https://kubernetes.default.svc"
            jenkinsUrl: "http://jenkins-service.jenkins.svc.cluster.local:8080"
            templates:
              - name: "gcp-agent"
                label: "gcp-agent"
                serviceAccount: "jenkins-sa"
                containers:
                  - name: "jnlp"
                    image: "jenkins/inbound-agent:latest"
                    workingDir: "/home/jenkins/agent"
                  - name: "build-tools"
                    image: "gcr.io/google.com/cloudsdktool/google-cloud-cli:slim"
                    command: "cat"
                    ttyEnabled: true
    credentials:
      system:
        domainCredentials:
          - credentials:
              - string:
                  scope: GLOBAL
                  id: "argocd-jenkins-token"
                  secret: "YOUR_ARGOCD_TOKEN_HERE"
                  description: "ArgoCD API Token for Jenkins Pipeline"
              - string:
                  scope: GLOBAL
                  id: "github-jenkins-token"
                  secret: "YOUR_GITHUB_TOKEN_HERE"
                  description: "GitHub Token for Status Checks or API Calls"
    unclassified:
      location:
        url: "https://jenkins.andrei-test.lendo.dev/"
    jobs:
      - script: |
          pipelineJob('gcp-app-ci-cd') {
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/onneyami/gcp-terraform-task-2.git')
                    }
                    branches('*/main')
                  }
                }
                scriptPath('Jenkinsfile')
              }
            }
          }