apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-config
  namespace: jenkins
data:
  jenkins.yaml: |
    jenkins:
      securityRealm:
        local:
          allowsSignup: false
          users:
            - id: "admin"
              password: "AdminPassword123!"
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          authenticatedUserReadPermission: true
    unclassified:
      location:
        url: "https://jenkins.andrei-test.lendo.dev/"