apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-config
  namespace: jenkins
data:
  jenkins.yaml: |
    jenkins:
      slaveAgentPort: 50000
      securityRealm:
        local:
          allowsSignup: false
          users:
            - id: "admin"
              password: "AdminPassword123!"
      authorizationStrategy:
        loggedInUsersCanDoAnything:
          allowAnonymousRead: false

    credentials:
      system:
        domainCredentials:
          - credentials:
              - string:
                  scope: GLOBAL
                  id: "argocd-jenkins-token"
                  secret: "${ARGOCD_TOKEN}"
                  description: "ArgoCD API Token for Jenkins Pipeline"
              - usernamePassword:
                  scope: GLOBAL
                  id: "github-jenkins-token"
                  username: "onneyami"
                  password: "${GITHUB_TOKEN}"
                  description: "GitHub Personal Access Token"

    unclassified:
      location:
        url: "https://jenkins.andrei-test.lendo.dev/"

    appearance:                  # <--- ALIGN WITH 'unclassified:' (NO EXTRA SPACES)
      themeManager:
        disableUserThemes: false
        theme: "dark"

    jobs:
      - script: |
          pipelineJob('gcp-app-ci-cd') {
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/onneyami/gcp-terraform-task-2.git')
                    }
                    branches('*/main')
                  }
                }
                scriptPath('Jenkinsfile')
              }
            }
          }