apiVersion: v1
kind: Pod
metadata:
  name: jenkins-gcp-test
  namespace: jenkins
spec:
  serviceAccountName: jenkins-sa # <--- Using your actual SA
  containers:
  - name: jenkins-agent
    image: google/cloud-sdk:slim
    command: ["sleep", "3600"]