apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-sa
  namespace: jenkins
  annotations:
    iam.gke.io/gcp-service-account: "jenkins-gsa@andrei-innowise-tests-120826.iam.gserviceaccount.com"