apiVersion: apps/v1
kind: Deployment
metadata:
  name: apod-api
  namespace: default
  labels:
    app: apod-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apod-api
  template:
    metadata:
      labels:
        app: apod-api
    spec:
      containers:
        - name: apod-api
          image: europe-north1-docker.pkg.dev/andrei-innowise-tests-120826/gke-repo/apod-api:v1.0.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 150m
              memory: 128Mi