apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: apod-api-secrets
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-backend
  target:
    name: apod-api-k8s-secret   # Name of created native K8s Secret
    creationPolicy: Owner
  data:
    - secretKey: NASA_API_KEY    # Key inside created K8s Secret
      remoteRef:
        key: nasa-api-key        # Secret name in GCP Secret Manager