jobs:
  - script: |
      pipelineJob('gcp-app-ci-cd') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GIT_REPO_URL:-https://github.com/onneyami/gcp-terraform-task-2.git}')
                }
                branches('*/main')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }