{
 "title": "Apod-api pod monitoring",
 "tags": [ "apod-api" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"apod-api.*\", container!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"apod-api.*\", container!=\"\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{pod=~\"apod-api.*\"}[1h])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}