apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 88.6.2
    helm:
      values: |
        grafana:
          adminPassword: "AdminPassword123!"
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
            hosts:
              - grafana.andrei-test.lendo.dev
            tls:
              - secretName: grafana-tls-cert
                hosts:
                  - grafana.andrei-test.lendo.dev
          sidecar:
            datasources:
              enabled: true
              defaultDatasourceEnabled: false
          additionalDataSources:
            - name: Prometheus
              type: prometheus
              uid: prometheus
              access: proxy
              url: http://prometheus-operated.monitoring.svc.cluster.local:9090
              isDefault: true
              jsonData:
                httpMethod: POST
                timeInterval: 15s

        prometheus:
          prometheusSpec:
            retention: 7d
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: standard-rwo
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 20Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true