apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-manifests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOUR_USER/YOUR_REPO.git' # Replace with your repo URL
    targetRevision: HEAD
    path: k8s-manifests/monitoring
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true