apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-config   # <--- Must be secrets-config, not external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/onneyami/gcp-terraform-task-2.git'
    targetRevision: dev
    path: k8s-manifests/secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true